#ifndef WINVERSION_H
#define WINVERSION_H

#define NTDDI_VERSION NTDDI_VISTA
#define _WIN32_WINNT  _WIN32_WINNT_VISTA
#define WINVER        _WIN32_WINNT_VISTA
#define _WIN32_IE     _WIN32_IE_IE80

#endif // WINVERSION_H
